name: CI
on: [push]

jobs:
  test:
    name: Test on ${{ matrix.platform }}
    runs-on: macos-latest
    strategy:
      matrix:
        platform: ["ios", "macos", "watchos", "tvos", "catalyst"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - run: make ${{ matrix.platform }}