name: CI
on: [push]

jobs:
  test:
    name: Test on ${{ matrix.platform }}
    strategy:
      matrix:
        platform: ["ios", "macos", "watchos", "tvos", "catalyst"]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Test"
        run: make ${{ matrix.platform }}